project:
  type: website
  output-dir: docs

website:
  title: "Trends in child mortality"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    anchor-sections: false

editor: visual

